# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1100, 827)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.BeamDisplay = MplWidget(self.centralWidget)
        self.BeamDisplay.setGeometry(QtCore.QRect(30, 280, 331, 311))
        self.BeamDisplay.setObjectName(_fromUtf8("BeamDisplay"))
        self.xplot = MplWidget(self.centralWidget)
        self.xplot.setGeometry(QtCore.QRect(30, 120, 331, 141))
        self.xplot.setObjectName(_fromUtf8("xplot"))
        self.yplot = MplWidget(self.centralWidget)
        self.yplot.setGeometry(QtCore.QRect(380, 280, 141, 311))
        self.yplot.setObjectName(_fromUtf8("yplot"))
        self.TwoD_region = QtGui.QGraphicsView(self.centralWidget)
        self.TwoD_region.setGeometry(QtCore.QRect(880, 450, 91, 91))
        self.TwoD_region.setObjectName(_fromUtf8("TwoD_region"))
        self.TwoD_fit = QtGui.QGraphicsView(self.centralWidget)
        self.TwoD_fit.setGeometry(QtCore.QRect(740, 470, 91, 81))
        self.TwoD_fit.setObjectName(_fromUtf8("TwoD_fit"))
        self.FitResultsHorizontal = QtGui.QTextBrowser(self.centralWidget)
        self.FitResultsHorizontal.setGeometry(QtCore.QRect(540, 160, 161, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.FitResultsHorizontal.setFont(font)
        self.FitResultsHorizontal.setObjectName(_fromUtf8("FitResultsHorizontal"))
        self.FitResultsVertical = QtGui.QTextBrowser(self.centralWidget)
        self.FitResultsVertical.setGeometry(QtCore.QRect(540, 340, 161, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.FitResultsVertical.setFont(font)
        self.FitResultsVertical.setObjectName(_fromUtf8("FitResultsVertical"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(420, 20, 331, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.StartButton = QtGui.QPushButton(self.centralWidget)
        self.StartButton.setGeometry(QtCore.QRect(30, 20, 115, 32))
        self.StartButton.setObjectName(_fromUtf8("StartButton"))
        self.PauseButton = QtGui.QPushButton(self.centralWidget)
        self.PauseButton.setGeometry(QtCore.QRect(160, 20, 115, 32))
        self.PauseButton.setObjectName(_fromUtf8("PauseButton"))
        self.fileDialog = QtGui.QPushButton(self.centralWidget)
        self.fileDialog.setGeometry(QtCore.QRect(500, 70, 115, 31))
        self.fileDialog.setObjectName(_fromUtf8("fileDialog"))
        self.fileOutput = QtGui.QTextBrowser(self.centralWidget)
        self.fileOutput.setGeometry(QtCore.QRect(30, 70, 461, 31))
        self.fileOutput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.fileOutput.setAcceptRichText(True)
        self.fileOutput.setObjectName(_fromUtf8("fileOutput"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(940, 730, 134, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.ErrorMessages = QtGui.QTextBrowser(self.centralWidget)
        self.ErrorMessages.setGeometry(QtCore.QRect(30, 630, 331, 91))
        self.ErrorMessages.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ErrorMessages.setObjectName(_fromUtf8("ErrorMessages"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(530, 120, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(540, 310, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(30, 600, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.PowerMeter = QtGui.QLCDNumber(self.centralWidget)
        self.PowerMeter.setGeometry(QtCore.QRect(380, 630, 191, 91))
        self.PowerMeter.setObjectName(_fromUtf8("PowerMeter"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(380, 600, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(600, 660, 51, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(750, 70, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pixelSizeInput = QtGui.QDoubleSpinBox(self.centralWidget)
        self.pixelSizeInput.setGeometry(QtCore.QRect(810, 100, 62, 22))
        self.pixelSizeInput.setDecimals(3)
        self.pixelSizeInput.setProperty("value", 1.0)
        self.pixelSizeInput.setObjectName(_fromUtf8("pixelSizeInput"))
        self.label_9 = QtGui.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(750, 140, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.rotationFitOn = QtGui.QCheckBox(self.centralWidget)
        self.rotationFitOn.setGeometry(QtCore.QRect(880, 140, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rotationFitOn.setFont(font)
        self.rotationFitOn.setObjectName(_fromUtf8("rotationFitOn"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(710, 170, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.beamRotationValue = QtGui.QLCDNumber(self.centralWidget)
        self.beamRotationValue.setGeometry(QtCore.QRect(820, 170, 64, 23))
        self.beamRotationValue.setObjectName(_fromUtf8("beamRotationValue"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(890, 170, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.fitFromFile = QtGui.QPushButton(self.centralWidget)
        self.fitFromFile.setGeometry(QtCore.QRect(290, 20, 101, 31))
        self.fitFromFile.setObjectName(_fromUtf8("fitFromFile"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menuBar.setMouseTracking(False)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.FitResultsHorizontal.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>", None))
        self.label.setText(_translate("MainWindow", "Python gaussian beam fitter", None))
        self.StartButton.setText(_translate("MainWindow", "Start", None))
        self.PauseButton.setText(_translate("MainWindow", "Pause", None))
        self.fileDialog.setText(_translate("MainWindow", "Choose file", None))
        self.label_2.setText(_translate("MainWindow", "Press Esc to exit", None))
        self.label_3.setText(_translate("MainWindow", "Horizontal axis fitting", None))
        self.label_4.setText(_translate("MainWindow", "Vertical axis fitting", None))
        self.label_5.setText(_translate("MainWindow", "Error messages", None))
        self.label_6.setText(_translate("MainWindow", "Power", None))
        self.label_7.setText(_translate("MainWindow", "mW", None))
        self.label_8.setText(_translate("MainWindow", "Cam pixel size (microns)", None))
        self.label_9.setText(_translate("MainWindow", "Fit beam rotation", None))
        self.rotationFitOn.setText(_translate("MainWindow", "Yes", None))
        self.label_10.setText(_translate("MainWindow", "Beam rotation", None))
        self.label_11.setText(_translate("MainWindow", "deg", None))
        self.fitFromFile.setText(_translate("MainWindow", "From File", None))

from mplwidget import MplWidget
